from enum import Enum, auto


class State(Enum):
    LIVE = auto()
    CLIP = auto()
    MENU = auto()
    MENU_CROSS = auto()
    MENU_CROSS_COLOR = auto()
    MENU_CROSS_COLOR_R = auto()
    MENU_CROSS_COLOR_G = auto()
    MENU_CROSS_COLOR_B = auto()
    MENU_CROSS_TYPE = auto()
    MENU_CROSS_TYPE_CROSS = auto()
    MENU_CROSS_TYPE_DOT = auto()
    MENU_CROSS_TYPE_HALO = auto()
    MENU_CROSS_X = auto()
    MENU_CROSS_Y = auto()
    MENU_VIEW_MODE = auto()
    MENU_VIEW_MODE_DAY = auto()
    MENU_VIEW_MODE_GRN_NIGHT = auto()
    MENU_VIEW_MODE_GREY_NIGHT = auto()
    MENU_VIDEO = auto()
    MENU_VIDEO_RES = auto()
    MENU_VIDEO_RES_720 = auto()
    MENU_VIDEO_RES_1080 = auto()
    MENU_VIDEO_FPS = auto()
    MENU_VIDEO_FPS_SET = auto()
    MENU_VIDEO_CLIP_BEFORE = auto()
    MENU_VIDEO_CLIP_BEFORE_SET = auto()
    MENU_VIDEO_CLIP_AFTER = auto()
    MENU_VIDEO_CLIP_AFTER_SET = auto()
    MENU_LANGUAGE = auto()
    MENU_LANGUAGE_CZ = auto()
    OFF = auto()
    
